insert into SEQUENCE (NAME) values ('PURCHASE_ORDER_NO_SEQ');
insert into SEQUENCE (NAME) values ('RECEIVING_RECEIPT_NO_SEQ');
insert into SEQUENCE (NAME) values ('PURCHASE_RETURN_BAD_STOCK_NO_SEQ');
insert into SEQUENCE (NAME) values ('PURCHASE_RETURN_NO_SEQ');
insert into SEQUENCE (NAME) values ('BIR_FORM_2307_REPORT_NO_SEQ');
insert into SEQUENCE (NAME) values ('PURCHASE_PAYMENT_NO_SEQ');
insert into SEQUENCE (NAME) values ('PURCHASE_PAYMENT_ADJUSTMENT_NO_SEQ');
insert into SEQUENCE (NAME) values ('CREDIT_CARD_STATEMENT_NO_SEQ');
insert into SEQUENCE (NAME) values ('ADJUSTMENT_OUT_NO_SEQ');
insert into SEQUENCE (NAME) values ('ADJUSTMENT_IN_NO_SEQ');

insert into USER
VALUES
(1, 'ADMIN', '9ojpu4j2w2obEO2QfwNaL3QhuhmNpWjgONyQ6LPlUVE=', 'Y', 'Y');

insert into SYSTEM_PARAMETER
values
('VERSION', '2.3.0');

insert into PURCHASE_PAYMENT_ADJ_TYPE (ID, CODE, DESCRIPTION) values (1, 'RETURN - GS', 'PURCHASE RETURN - GOOD STOCK');
insert into PURCHASE_PAYMENT_ADJ_TYPE (ID, CODE, DESCRIPTION) values (2, 'RETURN - BS', 'PURCHASE RETURN - BAD STOCK');
